name: PR on Resume

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install Arial font
        run: |
          echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
          sudo apt-get update
          sudo apt-get install -y ttf-mscorefonts-installer
          sudo fc-cache -f

      - name: Setup Typst
        uses: typst-community/setup-typst@v3

      - name: Compile Typst document
        run: typst compile resume.typ
